# Generated by Django 4.1.7 on 2023-04-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0005_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
