from django.urls import path, include
from . import views_access,views_profile, views_shop, views_shopping_cart, views_purchase, views_paypal

urlpatterns = [
    path('', views_shop.shop, name='shop'),
    path('login/', views_access.signin, name='signin'),
    path('register/', views_access.signup, name='signup'),
    path('logout/', views_access.signout, name='logout'),
    path('kitchen/', views_shop.kitchen, name='kitchen'),
    path('bathroom/', views_shop.bathroom, name='bathroom'),
    path('bedroom/', views_shop.bedroom, name='bedroom'),
    path('decor/', views_shop.decor, name='decor'),
    path('offers/', views_shop.offers, name='offers'),
    path('products/<str:text>', views_shop.get_products),
    path('<str:view_name>/description/<int:product_id>', views_shop.product_description, name='description'),
    path('profile/', views_profile.user_profile, name='profile'),
    path('profile/config', views_profile.user_config, name='config'),
    path('profile/config/confirm/<str:previous_view>/<str:previous_name>/<str:mode>', views_profile.confirm_user_config, name='confirm_user_config'),
    path('profile/payment', views_profile.user_payment, name='payment'),
    path('profile/payment/confirm/<str:previous_view>/<str:previous_name>/<str:mode>', views_profile.confirm_payment, name='confirm_payment'),
    path('profile/history', views_profile.shopping_history, name='history'),
    # path('profile/history/pdf', views_profile.show_pdf, name='history_pdf'),
    # path('profile/history/pdf', views_profile.show_pdf, name='history_pdf'),
    # path('profile/config/<str:username>', views_profile.change_username),
    # path('profile/config/change/password', views_profile.change_password),
    # path('profile/payment/add_payment_method', views_profile.add_payment_method),
    # path('profile/payment/remember_payment_method', views_profile.remember_payment_method),
    path('shopping_cart/', views_shopping_cart.shopping_cart, name='cart'),
    path('shopping_cart/<int:product_id>', views_shopping_cart.get_product_quantity_cart),
    path('shopping_cart/buy', views_purchase.buy_product, name='buy'),
    # path('shopping_cart/buy/<str:number>/<str:month>/<str:year>/<str:cvv>/<str:remember>', views_purchase.verify_card),
    path('shopping_cart/buy/confirm/<str:previous_view>/<str:previous_name>/<str:mode>', views_purchase.confirm_purchase, name='confirm_purchase'),
    path('shopping_cart/buy/<str:names>/<str:surnames>/<str:dni>/<str:address>', views_purchase.save_user_info),
    path('products/add_product/<int:product_id>', views_shopping_cart.add_product),
    path('products/remove_product_unit/<int:product_id>', views_shopping_cart.remove_product_unit),
    path('products/remove_product/<int:product_id>', views_shopping_cart.remove_product),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('paypal/payment', views_paypal.paypal, name='paypal'),
    path('paypal/successful', views_paypal.successful_payment, name='successful_payment'),
    path('paypal/error', views_paypal.payment_error, name='payment_error')
]