# Generated by Django 4.2.1 on 2023-05-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0002_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='updated_at',
        ),
    ]
