# Generated by Django 4.1.7 on 2023-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
