# Generated by Django 4.2.1 on 2023-05-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0004_alter_shoppingcart_options_alter_shoppingcart_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.JSONField(),
        ),
    ]
