# Generated by Django 4.2.1 on 2023-05-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0007_alter_product_stock'),
        ('Ventas_Retail', '0012_paymentcard_created_at'),
    ]

    operations = [
    ]
