# Generated by Django 4.2.1 on 2023-05-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0014_rename_username_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
