# Generated by Django 4.2.1 on 2023-05-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0016_shoppinghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingHistory',
        ),
    ]
