# Generated by Django 4.2.1 on 2023-06-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0019_delete_order'),
    ]

    operations = [
        
    ]
