# Generated by Django 4.2.1 on 2023-06-02 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0020_remove_userinfo_user_delete_shoppingcart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentCard',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
