# Generated by Django 4.2.1 on 2023-06-02 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Retail', '0021_remove_shoppingcart_user_remove_userinfo_user_and_more'),
        ('Ventas_Retail', '0022_userinfo_shoppingcart_paymentcard'),
    ]

    operations = [
    ]
